name: Tests

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install bot
      run: gem install awesome_bot
    - name: Run tests
      run: awesome_bot README.md --request-delay 1 --allow-dupe --white-list igor.io,symfony,toranproxy.com,vagrantup.com,3v4l.org,voicesoftheelephpant.com,drupal.org,oreilly.com,youtube.com,lumen.laravel.com
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: ab-results
        path: ab-results-README.md-filtered.json

    - name: Read/Write data into output.md
      uses: eddiejaoude/github-actions-reader-writer@v0.1
      with:
        json-file-path: 'ab-results-README.md-filtered.json'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        columns: 5
        object-field-names: '[ "loc", "status", "link", "redirect", "error" ]'
        file-to-use: 'output.md'
        html-cell: '<td align="center">{{ loc }} {{status}} {{link}} {{redirect}} {{error}}</td>'

    - name: comment PR
      uses: machine-learning-apps/pr-comment@master
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: output.md
