name: Receive PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install bot
      run: gem install awesome_bot

    - name: create whatchanged.md
      run: git diff origin/master origin/${GITHUB_HEAD_REF} -- README.md | grep '^[+]' | grep -Ev '^(--- a/|\+\+\+ b/)' | sed -e 's/^+//' > whatchanged.md

    - name: Run tests
      run: awesome_bot whatchanged.md --request-delay 1 --allow-dupe --white-list igor.io,symfony,toranproxy.com,vagrantup.com,3v4l.org,voicesoftheelephpant.com,drupal.org,oreilly.com,youtube.com,lumen.laravel.com --allow 301,302 || true
    - uses: actions/upload-artifact@v1
      with:
        name: ab-results
        path: ab-results-whatchanged.md-filtered.json

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Save PR number
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/NR

    - name: generate ab-results-output.md
      run: python a.py

    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/
